id = "shades-of-purple"
name = "Shades of Purple"
version = "0.1.0"
schema_version = 1
authors = ["mahi160 omarsifat288@gmail.com"]
description = "Shades of purple theme for Zed"
repository = "https://github.com/mahi160/shades-of-purple"
